export const TID = {
  loginEmail: "login-email-input",
  loginPassword: "login-password-input",
  loginSubmit: "login-submit-button",
  loginDemo: "login-demo-shortcut",
  logout: "logout-button",
  sidebar: "app-sidebar",
  navDashboard: "nav-dashboard",
  navCrm: "nav-crm",
  navClients: "nav-clients",
  navContent: "nav-content",
  navPortal: "nav-portal",
  dashboard: "dashboard-page",
  kpiActive: "kpi-active-clients",
  kpiMrr: "kpi-mrr",
  kpiLeads: "kpi-leads",
  kpiAwaiting: "kpi-awaiting-approval",
  crmPage: "crm-page",
  crmNewLead: "crm-new-lead-btn",
  crmConvert: "crm-convert-lead",
  clientsPage: "clients-page",
  clientCard: "client-card",
  contentKanban: "content-kanban",
  contentSendApproval: "content-send-approval",
  approveBtn: "content-approve-btn",
  adjustBtn: "content-adjust-btn",
  portalPage: "portal-page",
};
